AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla tarea 4_2_1 Alex"
Parameters:

  CreateEC2:
    Description: "Create EC2 instance"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  InstanceType:
    Description: "Instance type"
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t2.small"
      - "t2.medium"

Rules:
  TypeEc2:
    Assertions:
      - Assert:
          "Fn::Contains":
            - ["t2.micro", "t2.small", "t2.medium"]
            - !Ref InstanceType
    Assert: "true"

Conditions:
  CreateEC2: !Equals [!Ref CreateEC2, "true"]

Resources:
  # VPC
  VPCAlex:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-Alex

  # Subred pública
  PublicSubnetAlex:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCAlex
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-Alex

  # EC2 Instance
  EC2AlexInstance:
    Type: AWS::EC2::Instance
    Condition: CreateEC2
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      ImageId: "ami-04b4f1a9cf54c11d0"
      InstanceType: !Ref InstanceType
      KeyName: vockey
      SubnetId: !Ref PublicSubnetAlex
      Tags:
        - Key: Name
          Value: !Join ["-", [!GetAtt PublicSubnetAlex.AvailabilityZone, !Ref "AWS::Region"]]
        - Key: VPCID
          Value: !GetAtt VPCAlex.VpcId
